# -*- coding: utf-8 -*-
"""client.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wA9vTHvb5pHDx5ZvMbpI_0ltD-y43Fhp
"""

import socket 

HOST = '127.0.0.1'
PORT = 50000

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect((HOST, PORT))
s.sendall(str.encode('Olá Mundo'))
data = s.recv(1024)

print('Conexão cliente servidor realizada com sucesso! \nMessage:', data.decode())
s.close()