# -*- coding: utf-8 -*-
"""server.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/179yXTWzWtlOIQn-8dxQfFMQ6ybSYQsUm
"""

import socket 

HOST = 'localhost'
PORT = 50000

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

s.bind((HOST, PORT))

s.listen()

print('Aguardando conexão de um cliente')

connection, address = s.accept()

print('Conectado em', address)

while True:
  data = connection.recv(1024)
  if not data:
    print('Fechando a conexão')
    connection.close()
    break
  connection.sendall(data)
s.close()